default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV.fetch('ROCKAUTH_DB_HOST', 'localhost') %>
  username: <%= ENV.fetch('ROCKAUTH_DB_USERNAME', 'root') %>
  password: <%= ENV.fetch('ROCKAUTH_DB_PASSWORD', 'null') %>

development:
  <<: *default
  database: <%= ENV.fetch('ROCKAUTH_DB_NAME', 'rockauth_development') %>

test:
  <<: *default
  database: <%= ENV.fetch('ROCKAUTH_TEST_DB_NAME', 'rockauth_test') %>
